/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        NButton: (typeof import('naive-ui'))['NButton'];
        NCarousel: (typeof import('naive-ui'))['NCarousel'];
        NConfigProvider: (typeof import('naive-ui'))['NConfigProvider'];
        NDataTable: (typeof import('naive-ui'))['NDataTable'];
        NDatePicker: (typeof import('naive-ui'))['NDatePicker'];
        NDialogProvider: (typeof import('naive-ui'))['NDialogProvider'];
        NMessageProvider: (typeof import('naive-ui'))['NMessageProvider'];
        NModal: (typeof import('naive-ui'))['NModal'];
        NNotificationProvider: (typeof import('naive-ui'))['NNotificationProvider'];
        NPagination: (typeof import('naive-ui'))['NPagination'];
        NSpace: (typeof import('naive-ui'))['NSpace'];
        NTable: (typeof import('naive-ui'))['NTable'];
        NTooltip: (typeof import('naive-ui'))['NTooltip'];
        RouterLink: (typeof import('vue-router'))['RouterLink'];
        RouterView: (typeof import('vue-router'))['RouterView'];
    }
}
