/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        AButton: (typeof import('ant-design-vue/es'))['Button'];
        ACarousel: (typeof import('ant-design-vue/es'))['Carousel'];
        AConfigProvider: (typeof import('ant-design-vue/es'))['ConfigProvider'];
        AModal: (typeof import('ant-design-vue/es'))['Modal'];
        APagination: (typeof import('ant-design-vue/es'))['Pagination'];
        ATable: (typeof import('ant-design-vue/es'))['Table'];
        ATooltip: (typeof import('ant-design-vue/es'))['Tooltip'];
        RouterLink: (typeof import('vue-router'))['RouterLink'];
        RouterView: (typeof import('vue-router'))['RouterView'];
    }
}
